name: CI for FizzBuzz

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 1  # タイムアウト設定（1分）

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flake8 pylint mypy bandit pytest

      - name: Run flake8 (Style Check)
        run: |
          set -euxo pipefail
          source venv/bin/activate
          flake8 fizzbuzz.py

      - name: Run pylint (Code Quality)
        run: |
          set -euxo pipefail
          source venv/bin/activate
          pylint fizzbuzz.py

      - name: Run mypy (Type Check)
        run: |
          set -euxo pipefail
          source venv/bin/activate
          mypy fizzbuzz.py

      - name: Run bandit (Security Check)
        run: |
          set -euxo pipefail
          source venv/bin/activate
          bandit -r fizzbuzz.py

      - name: Run tests
        run: |
          set -euxo pipefail
          source venv/bin/activate
          pytest tests/
