name: Python Lint & Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flake8 pylint mypy bandit

      - name: Run flake8 (Style Check)
        run: |
          source venv/bin/activate
          flake8 fizzbuzz.py

      - name: Run pylint (Code Quality)
        run: |
          source venv/bin/activate
          pylint fizzbuzz.py

      - name: Run mypy (Type Check)
        run: |
          source venv/bin/activate
          mypy fizzbuzz.py

      - name: Run bandit (Security Check)
        run: |
          source venv/bin/activate
          bandit -r fizzbuzz.py
